import Sidebar from "./Sidebar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function DashbrdLayout({ children }) {
  return (
    <div className="flex flex-no-wrap">
      <Sidebar />
      <div className="md:py-10 flex-1 md:px-6">
        <div className="w-full h-full rounded border-dashed border-2 border-gray-300">
          {children}
        </div>
      </div>
    </div>
  );
}
